-- Catalogo Autodealer: 26 auto (27 schede contando i due colori della Mustang).
-- Generato dal database locale. id, created_at e updated_at sono rigenerati
-- all'inserimento, cosi' lo script vale su qualunque ambiente.
--
-- Uso su Render, con la "External Database URL" presa dalla dashboard del database:
--   psql "<external-database-url>" -f db/seed-catalogo.sql
--
-- Ripetibile: le auto gia' presenti non vengono duplicate.

BEGIN;

INSERT INTO cars (id, marca, modello, descrizione, prezzo_acquisto, prezzo_vendita, is_bozza, version, created_at, updated_at)
SELECT gen_random_uuid(), v.marca, v.modello, v.descrizione, v.prezzo_acquisto, v.prezzo_vendita, false, 0,
       now() - (v.ordine * interval '1 hour'), now() - (v.ordine * interval '1 hour')
FROM (VALUES
  ('Ford', 'Shelby GT500 Extreme', 'Configurazione in edizione speciale unica, uno di uno. Il vertice assoluto dell''ingegneria muscle car americana: V8 Predator assemblato a mano, pacchetto aerodinamico Carbon Fiber Track e impianto frenante Brembo sovradimensionato. Un investimento da collezionista destinato a fare la storia.', 720000.00, 1000000.00, 1),
  ('Ford', 'Shelby GT500', 'La Mustang di serie più potente e performante mai creata da Ford Performance. Il mostruoso V8 Predator sovralimentato con compressore volumetrico e il cambio a doppia frizione derivato dal programma Ford GT la rendono il vertice dell''ingegneria muscle car americana.', 118000.00, 152000.00, 2),
  ('Volkswagen', 'Golf R', 'La regina delle hot hatch. La Golf R combina la praticità, la tecnologia e lo spazio di una cinque porte per tutti i giorni con la potenza e la trazione di una sportiva da pista, modalità Drift inclusa.', 52000.00, 53000.00, 3),
  ('Citroen', 'C3', 'La compatta che democratizza il comfort e la mobilità moderna. Con il look d''ispirazione crossover, l''altezza da terra aumentata e le sospensioni Advanced Comfort, la C3 assorbe qualsiasi imperfezione stradale offrendo un rapporto qualità prezzo imbattibile.', 14200.00, 19900.00, 4),
  ('Toyota', 'Yaris Hybrid', 'Eletta Auto dell''Anno 2021, la Yaris è il riferimento assoluto per la tecnologia full-hybrid. Ideale per chi cerca consumi bassissimi in città senza il vincolo di dover ricaricare la batteria a una presa.', 16800.00, 22500.00, 5),
  ('Fiat', '500e', 'La regina indiscussa del traffico cittadino. Nella variante 100% elettrica la 500 offre uno stile inconfondibile, interni curati e la massima agilità nei parcheggi e nei vicoli più stretti, con ricarica rapida e costi di esercizio ridotti.', 18900.00, 25400.00, 6),
  ('Aston Martin', 'Valkyrie', 'Una Formula 1 con i fari e la targa. Disegnata dal genio dell''aerodinamica Adrian Newey, impiega il V12 aspirato stradale con il regime di rotazione più alto del mondo, abbinato a un sistema aerodinamico ad effetto suolo estremo.', 3100000.00, 3600000.00, 7),
  ('Koenigsegg', 'Jesko', 'Capolavoro di ingegneria svedese senza pari. Sviluppata per rompere la barriera dei 480 km/h, adotta l''innovativo cambio Light Speed Transmission a nove marce e sette frizioni, che consente di saltare istantaneamente a qualsiasi rapporto senza perdita di coppia.', 3900000.00, 4500000.00, 8),
  ('Porsche', '918 Spyder', 'La prima vettura ad aver dimostrato che la tecnologia ibrida plug-in poteva dominare al Nürburgring. Con lo scarico posizionato sopra la testa degli occupanti e la trazione integrale elettrica, permette di viaggiare a zero emissioni in città o scatenare 887 cavalli in pista.', 1450000.00, 1750000.00, 9),
  ('Ferrari', 'LaFerrari', 'La prima hypercar ibrida della casa di Maranello, prodotta in soli 499 esemplari. Abbina un V12 da 6,5 litri al sistema HY-KERS derivato dalla Formula 1 per erogare 963 cavalli complessivi.', 3600000.00, 4200000.00, 10),
  ('Bugatti', 'Chiron', 'L''evoluzione suprema dell''automobile a combustione interna. Con 1.500 cavalli a referto e una velocità massima limitata a 420 km/h, la Chiron rappresenta il vertice assoluto dell''ingegneria, dell''artigianalità e del lusso.', 3400000.00, 3950000.00, 11),
  ('Ford', 'Bronco', 'Il ritorno di una leggenda dell''off-road americano. Pensato per gli amanti dell''avventura e della natura: porte e tetto si smontano completamente in poche mosse per guidare a cielo aperto su qualsiasi terreno.', 58000.00, 76500.00, 12),
  ('Tesla', 'Model X Plaid', 'Il SUV elettrico più avveniristico e performante del pianeta. Con le iconiche portiere posteriori Falcon Wing e oltre mille cavalli, Model X garantisce scatti da monoposto elettrica uniti a un abitacolo confortevole fino a sette posti.', 78000.00, 98500.00, 13),
  ('Ferrari', 'Purosangue', 'La prima quattro porte e quattro posti della storia del Cavallino Rampante. Equipaggiata con un maestoso V12 aspirato da 725 cavalli in posizione anteriore-centrale, la Purosangue non è un classico SUV ma una vera auto sportiva ad assetto rialzato.', 465000.00, 540000.00, 14),
  ('Land Rover', 'Defender 110', 'La completa reinvenzione di un fuoristrada leggendario. Il nuovo Defender mantiene le straordinarie doti off-road del suo antenato, aggiungendo telaio in alluminio, sospensioni pneumatiche e interni ultra-tecnologici, ideali per i lunghi viaggi asfaltati come per le piste più impervie.', 71000.00, 98000.00, 15),
  ('Lamborghini', 'Urus', 'Il primo Super SUV del mondo. Combina le prestazioni di una supersportiva di Sant''Agata Bolognese con la versatilità, l''altezza da terra e lo spazio per cinque passeggeri. Per chi non vuole scendere a compromessi tra divertimento di guida e utilizzo quotidiano in famiglia.', 198000.00, 245000.00, 16),
  ('Porsche', 'Carrera GT', 'Nata da un progetto destinato originariamente alla 24 Ore di Le Mans. Uno dei V10 aspirati dal suono più bello e acuto mai prodotti, cambio manuale con pomello in faggio e monoscocca in fibra di carbonio. La supercar per i veri puristi della guida manuale.', 1350000.00, 1650000.00, 17),
  ('Bugatti', 'Veyron 16.4', 'La vettura che ha infranto ogni barriera ingegneristica superando i mille cavalli e i quattrocento orari. La Veyron unisce la velocità di un caccia alla raffinatezza e alla facilità di guida di una berlina di gran lusso. Possederla significa avere la pietra miliare dell''automobilismo moderno.', 1250000.00, 1580000.00, 18),
  ('McLaren', 'F1', 'Progettata dal genio della Formula 1 Gordon Murray, è da molti considerata la più grande auto sportiva mai costruita. Guida centrale a tre posti, vano motore rivestito in foglia d''oro e V12 aspirato BMW M. Detiene ancora il record di auto con motore aspirato più veloce della storia.', 17500000.00, 19800000.00, 19),
  ('Ferrari', 'F40', 'L''ultima vettura approvata personalmente dal Drake, Enzo Ferrari. Creata per celebrare i quarant''anni della casa di Maranello, la F40 è la quintessenza dell''auto da corsa omologata per la strada: niente servosterzo, niente ABS, carrozzeria in kevlar e carbonio e un biturbo dalla spinta brutale.', 2150000.00, 2700000.00, 20),
  ('Lamborghini', 'Countach LP400', 'L''auto che ha rivoluzionato per sempre il concetto di supercar, inventando le portiere a forbice e la silhouette a cuneo firmata Marcello Gandini per Bertone. La Countach è la supercar per eccellenza: selvaggia, rumorosa, priva di compromessi ed esaltante da guidare.', 690000.00, 895000.00, 21),
  ('Chevrolet', 'Bel Air 1957', 'La regina del rock and roll americano e delle cromature anni Cinquanta. Il modello 1957 rappresenta l''apice del design statunitense d''epoca, con le inconfondibili pinne posteriori e il muso imponente. Perfetta per sfilate ed eventi, e per chi desidera una presenza su strada spettacolare.', 48000.00, 68000.00, 22),
  ('Fiat', 'Nuova 500 Prima Serie', 'Il capolavoro di Dante Giacosa che ha messo su ruote l''Italia del dopoguerra. La prima serie del 1957, con le caratteristiche porte controvento, è il simbolo del design italiano essenziale. L''auto storica d''ingresso perfetta: simpatica, facilissima da gestire e amata in tutto il mondo.', 16500.00, 24500.00, 23),
  ('Alfa Romeo', '2000 Spider Touring', 'L''incarnazione perfetta della Dolce Vita italiana. Carrozzata dalla celebre Touring di Milano con il metodo Superleggera, unisce linee filanti e aristocratiche a un propulsore bialbero reattivo. Ideale per le passeggiate estive e per chi vuole vivere l''eleganza d''altri tempi.', 82000.00, 115000.00, 24),
  ('Porsche', '911 Prima Serie', 'Il punto di partenza di una leggenda che dura da oltre sei decenni. Presentata al Salone di Francoforte del 1963, la prima 911 rappresenta la purezza concettuale del boxer raffreddato ad aria montato a sbalzo. La scelta d''obbligo per il collezionista che desidera partecipare ai concorsi d''eleganza e ai rally storici più prestigiosi.', 198000.00, 265000.00, 25),
  ('Ford', 'Mustang 1965', 'La muscle car americana per eccellenza. Nata dal genio di Lee Iacocca, la prima generazione della Mustang ha definito un''era di libertà e stile. Mettersi al volante di una Mustang degli anni Sessanta significa guidare un''icona del cinema e della cultura pop, con il rombo inconfondibile del V8 americano e un valore in crescita costante.', 41000.00, 58000.00, 26)
) AS v(marca, modello, descrizione, prezzo_acquisto, prezzo_vendita, ordine)
WHERE NOT EXISTS (SELECT 1 FROM cars c WHERE c.marca = v.marca AND c.modello = v.modello);

COMMIT;
